web: supervisord -c /etc/supervisor/conf.d/supervisord.conf -n
worker: php bin/console messenger:consume async --time-limit=3600 --memory-limit=256M
release: php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
