<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119091948 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_keys (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key_hash VARCHAR(64) NOT NULL, key_prefix VARCHAR(12) NOT NULL, scopes JSON NOT NULL, environment VARCHAR(20) NOT NULL, label VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9579321F57BFB971 ON api_keys (key_hash)');
        $this->addSql('CREATE INDEX IDX_9579321F166D1F9C ON api_keys (project_id)');
        $this->addSql('CREATE INDEX idx_api_key_hash ON api_keys (key_hash)');
        $this->addSql('CREATE TABLE issues (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, public_id UUID NOT NULL, fingerprint VARCHAR(64) NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, title VARCHAR(255) NOT NULL, culprit TEXT DEFAULT NULL, severity VARCHAR(20) DEFAULT NULL, occurrence_count INT NOT NULL, affected_users INT NOT NULL, first_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSON DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DA7D7F83B5B48B91 ON issues (public_id)');
        $this->addSql('CREATE INDEX IDX_DA7D7F83166D1F9C ON issues (project_id)');
        $this->addSql('CREATE INDEX idx_issue_fingerprint ON issues (fingerprint)');
        $this->addSql('CREATE INDEX idx_issue_project_status ON issues (project_id, status)');
        $this->addSql('CREATE INDEX idx_issue_last_seen ON issues (last_seen_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_project_fingerprint ON issues (project_id, fingerprint)');
        $this->addSql('CREATE TABLE organization_memberships (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B606E30DA76ED395 ON organization_memberships (user_id)');
        $this->addSql('CREATE INDEX IDX_B606E30D32C8A3DE ON organization_memberships (organization_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_org ON organization_memberships (user_id, organization_id)');
        $this->addSql('CREATE TABLE organizations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, public_id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_427C1C7FB5B48B91 ON organizations (public_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_427C1C7F989D9B62 ON organizations (slug)');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, public_id UUID NOT NULL, name VARCHAR(255) NOT NULL, bundle_identifier VARCHAR(255) DEFAULT NULL, platform VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A4B5B48B91 ON projects (public_id)');
        $this->addSql('CREATE INDEX IDX_5C93B3A47E3C61F9 ON projects (owner_id)');
        $this->addSql('CREATE INDEX IDX_5C93B3A432C8A3DE ON projects (organization_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE api_keys ADD CONSTRAINT FK_9579321F166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE issues ADD CONSTRAINT FK_DA7D7F83166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization_memberships ADD CONSTRAINT FK_B606E30DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization_memberships ADD CONSTRAINT FK_B606E30D32C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A432C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE api_keys DROP CONSTRAINT FK_9579321F166D1F9C');
        $this->addSql('ALTER TABLE issues DROP CONSTRAINT FK_DA7D7F83166D1F9C');
        $this->addSql('ALTER TABLE organization_memberships DROP CONSTRAINT FK_B606E30DA76ED395');
        $this->addSql('ALTER TABLE organization_memberships DROP CONSTRAINT FK_B606E30D32C8A3DE');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A47E3C61F9');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A432C8A3DE');
        $this->addSql('DROP TABLE api_keys');
        $this->addSql('DROP TABLE issues');
        $this->addSql('DROP TABLE organization_memberships');
        $this->addSql('DROP TABLE organizations');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
